set_property PACKAGE_PIN A8 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports y]
set_property PACKAGE_PIN H5 [get_ports y]
set_property PACKAGE_PIN C11 [get_ports b]
